# SPDX-FileCopyrightText: 2025 Johnny Jazeix <jazeix@gmail.com>
# SPDX-License-Identifier: CC0-1.0

job:on-schedule:
  image: invent-registry.kde.org/sysadmin/ci-images/suse-qt610:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  tags:
    - Linux
  before_script:
    - git clone https://invent.kde.org/sdk/pology.git --depth=1
    - mkdir -p l10n-support/scripts
    - svn co svn://anonsvn.kde.org/home/kde/trunk/l10n-support/scripts l10n-support/scripts
  script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
    - ./run_gather.sh
